### ISSUE TITLE
Epic Loot incompatibility

### ISSUE THREAD

**Issue by Retifox** [blaxxun-boop/DualWield#10]
Can we get a version of mod that works with Epic Loot? I particularly don't mind the "cheating" aspect. I just want to have some fun with mates on sever :)

**Comment by blaxxun-boop** [comment]
No, sorry. Epic Loot is buggy as hell, not maintained for well over a year now and more and more mods will make themselves incompatible with Epic Loot. This is just the beginning. Just replace Epic Loot with Jewelcrafting.
