### ISSUE TITLE
not working with the game pass version.

### ISSUE THREAD

**Issue by UnslimShady22** [blaxxun-boop/DualWield#12]
Hey, I've downloaded this mod to try it out on the game pass edition of the game, and its not working, ever other mod seems to be working fine, but i cant get it working. Any particular things i have to do to make it work?

**Comment by blaxxun-boop** [comment]
I am using the gamepass version of Valheim as well and DualWield works perfectly fine.
Make sure you aren't using Epic Loot. Dual Wield doesn't work with Epic Loot.
