### ISSUE TITLE
error loading mod

### ISSUE THREAD

**Issue by dfkvrs** [blaxxun-boop/DualWield#19]
Getting the error message that is will not load. Saying its incompatible with BelpnExPack

**Comment by blaxxun-boop** [comment]
No, it's not incompatible with BepInEx (the modding framework used by all mods, including DualWield). It's incompatible with Valheim Plus, which is just another (terrible) mod. You don't need Valheim Plus to play modded.

**Comment by dfkvrs** [comment]
Ok thanks after looking at the data log closely I noticed that. Sorry about
that
