### ISSUE TITLE
Dual Wield Incompatible with  ValheimPlus+

### ISSUE THREAD

**Issue by Marioindy** [blaxxun-boop/DualWield#20]
Valheim Version :  0.212.9

Dual Wield Version :  1.0.6
ValheimPlus+ Version:  9.9.11

[Error  :   BepInEx] Could not load [Dual Wield 1.0.6] because it is incompatible with: org.bepinex.plugins.valheim_plus

**Comment by blaxxun-boop** [comment]
https://github.com/blaxxun-boop/PassivePowers/issues/5
