### ISSUE TITLE
Incompatibility: ValheimPlus

### ISSUE THREAD

**Issue by D1srupt3d** [blaxxun-boop/DualWield#21]
Does not work with ValheimPlus. Any chance it will in the future?

**Comment by blaxxun-boop** [comment]
No.

Read this, if you wanna know why: https://github.com/blaxxun-boop/PassivePowers/issues/5

**Comment by D1srupt3d** [comment]
Thanks. I actually ended up removing Valheim+ and found different mods to do what I needed. So Dual Wield is working now.

**Comment by blaxxun-boop** [comment]
Glad to hear that you are free now.
