### ISSUE TITLE
Got some Error Messages on loggin

### ISSUE THREAD

**Issue by Ernb4s** [blaxxun-boop/DualWield#3]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DualWield.DualWield+Patch_VisEquipment_AttachBackItem.Postfix (VisEquipment __instance, UnityEngine.Transform joint) (at <ac91807a96d548ee9ff60b7d05d46513>:0)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::AttachItem>(VisEquipment,int,int,UnityEngine.Transform,bool)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::SetRightHandEquiped>(VisEquipment,int)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::UpdateEquipmentVisuals>(VisEquipment)
VisEquipment.UpdateVisuals () (at <0b427da81d26480c885ae3fba0ed94c4>:0)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::Start>(VisEquipment)

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
DualWield.DualWield+Patch_VisEquipment_AttachBackItem.Postfix (VisEquipment __instance, UnityEngine.Transform joint) (at <ac91807a96d548ee9ff60b7d05d46513>:0)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::AttachItem>(VisEquipment,int,int,UnityEngine.Transform,bool)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::SetRightHandEquiped>(VisEquipment,int)
(wrapper dynamic-method) VisEquipment.DMD<VisEquipment::UpdateEquipmentVisuals>(VisEquipment)
VisEquipment.UpdateVisuals () (at <0b427da81d26480c885ae3fba0ed94c4>:0)
VisEquipment.Update () (at <0b427da81d26480c885ae3fba0ed94c4>:0)

**Comment by Ernb4s** [comment]
[Lots of Errors.log](https://github.com/blaxxun-boop/DualWield/files/8158575/Lots.of.Errors.log)

Well not only  on login, all the time also during the Bonmass Fight

**Comment by blaxxun-boop** [comment]
Has been fixed in v1.0.1
