### ISSUE TITLE
Server Sync not working

### ISSUE THREAD

**Issue by Peppychung** [blaxxun-boop/DualWield#4]
For some reason, whenever I change the values and upload them to my server, the server doesn't register the new damage values. It keeps going back to the default ones. It works just fine when I change the values locally. I even took the same file I had uploaded to the server and used that on a local world and the changes were implemented just fine.

The configuration lock is on as well.

**Comment by blaxxun-boop** [comment]
If you want to change BepInEx configs with replacing the file, make sure that your server isn't running while you upload those files or the server will write back the last known config on shutdown and overrides your configs.

I'd recommend to either use the [BepInEx Config Manager](https://valheim.thunderstore.io/package/Azumatt/Official_BepInEx_ConfigurationManager), which lets you press F1, while in the game, to change the configs live (no restart required and the configs will be active instantly for everyone who is connected). Make sure to connect to the server first, to change the servers configs and not your local config.

Or you could use the [Config Watcher](https://valheim.thunderstore.io/package/Smoothbrain/ConfigWatcher), which lets you update the config files on the server, without having to restart the server for your changes to take effect. Same effect here, upon overwriting or saving the config file on the server, it will be instantly reloaded and active for each connected client. Note the special installation instructions. This is a patcher and goes into the patchers folder, not the plugins folder.

Hope this helps.
