### ISSUE TITLE
Weird interactions with Skyheim

### ISSUE THREAD

**Issue by Oosquai** [blaxxun-boop/DualWield#8]
Rune with the same skill (Fire runes, for example), get dual wielded, and it's bad.  If running both mods, you're forced to unequip one fire rune before trying to switch to another.  Is there anyway to exclude the runes from Skyheim in the dual wield code please?

Here they are, if it helps:
rune_blink
rune_chain_lightning
rune_firebolt
rune_force
rune_frostbolt
rune_frostnova
rune_glacial_spike
rune_heal
rune_immolate
rune_invigorate
rune_light
rune_recall
rune_travel
rune_warmth

Thanks!

**Comment by Oosquai** [comment]
The staves from Sage's Vault share a similar issue.  Any chance you can update DualWield to make sure it only ever interacts with swords, knives, axes, and clubs please?

**Comment by blaxxun-boop** [comment]
That's exactly how it works already. Any issues with other mods weapons means that the mod author tagged the weapons as a sword or whatever. You would have to ask the author of Skyheim to fix this.

**Comment by Oosquai** [comment]
Hi blaxxun-boop!  Thanks so much for replying!  I'll ask.  But...  any chance you could add something to the config file that would allow us to exclude items by name?  Like...
dw_exclude_names:  "rune_firemagic", "rune_frostbolt"

**Comment by Oosquai** [comment]
Hi again blaxxun-boop!  Still hoping you like the idea of an exclusion string in the config file...  Thank you!

**Comment by Oosquai** [comment]
Updates!  I was wrong about Sage's Vault staves - they're not affected by Dual Wield.

The runes from Skyheim are though.  I asked on both the Skyheim and Skyheim Extended Posts pages for help a week ago, but I'm not getting any replies.  I'm not sure either author is still checking.

Any chance you'd consider the suggestion above about adding a hook in the Dual Wield config file to exclude items by name please?

Thank you!

**Comment by blaxxun-boop** [comment]
You can now exclude prefabs from being dual wielded in the config.

**Comment by Oosquai** [comment]
Thank you!!!  Except...  any way you could allow me to load it with Epic Loot still?  Pretty please?
